--- 
excluded_pkgfiles: []

project_pubdir: /usr/local/www/public/code/
project_pubhost: deveiate.org
project_homepage: http://rubygems.org/gems/sysexits
project_requirements: {}

release_smtphost: mail.faeriemud.org
project_description: |-
	Have you ever wanted to call exit() with an error condition, but
	weren't sure what exit status to use?  No? Maybe it's just me, then.
	
	Anyway, I was reading manpages late one evening before retiring to 
	bed in my palatial estate in rural Oregon, and I stumbled across 
	sysexits(3). Much to my chagrin, I couldn't find a 'sysexits' for
	Ruby! Well, for the other 2 people that actually care about style(9) 
	as it applies to Ruby code, now there is one!

release_mailto: Ruby-Talk List <ruby-talk@ruby-lang.org>
project_dependencies: {}

project_summary: Exit status codes for system programs.
version_file: sysexits.rb
additional_pkgfiles: []

dev_dependencies: 
  rake-compiler: ">=0"
authors: 
  Michael Granger: ged@FaerieMUD.org
post_install_message: Happy exiting!
project_name: sysexits
