--- 
excluded_pkgfiles: []

project_pubdir: /usr/local/www/public/code/
project_pubhost: deveiate.org
project_homepage: http://rubygems.org/gems/sysexits
project_requirements: {}

release_smtphost: mail.faeriemud.org
project_description: |-
  Have you ever wanted to call exit() with an error condition, but weren't sure what
  number to use? No? Maybe it's just me, then.
   
  Anyway, I was reading W. Richard Stephens's book _Advanced Programming in the UNIX Environment_, and
  I wanted to make my program exit with a reasonable exit code just like his C examples, but much
  to my chagrin, I couldn't find a 'sysexits' for Ruby! Well, for the other 2 people that actually
  care about this kind of thing, now there is!
release_mailto: Ruby-Talk List <ruby-talk@ruby-lang.org>
project_dependencies: {}

project_summary: A Ruby front end to sysexits.h
version_file: sysexits.rb
additional_pkgfiles: []

dev_dependencies: 
  rake-compiler: ">=0"
authors: 
  Michael Granger: ged@FaerieMUD.org
post_install_message: Happy exiting!
project_name: sysexits
